# Generated by Django 5.0.6 on 2024-06-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("nt", "Networking"),
                    ("web", "Web Development"),
                    ("ml", "Machine Learning"),
                    ("cl", "Cloud"),
                ],
                max_length=5,
            ),
        ),
    ]
